using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Interop;
using System.Windows.Media;

namespace DJLibrary
{
    internal static class GridGovernance
    {
        private static readonly DependencyProperty ConfiguredProperty = DependencyProperty.RegisterAttached(
            "Configured", typeof(bool), typeof(GridGovernance), new PropertyMetadata(false));

        public static void Apply(DataGrid grid)
        {
            if (grid == null) throw new ArgumentNullException("grid");
            grid.CanUserReorderColumns = true;
            grid.CanUserResizeColumns = true;
            grid.CanUserSortColumns = true;
            grid.EnableRowVirtualization = true;
            grid.EnableColumnVirtualization = false;
            grid.SelectionMode = DataGridSelectionMode.Single;
            grid.SelectionUnit = DataGridSelectionUnit.FullRow;
            ScrollViewer.SetHorizontalScrollBarVisibility(grid, ScrollBarVisibility.Auto);
            ScrollViewer.SetVerticalScrollBarVisibility(grid, ScrollBarVisibility.Auto);
            GridRuntimeSupport.ConfigureClipboard(grid);
            HorizontalScrollSupport.Enable(grid);
            EnsureColumnReadability(grid);

            if (!(bool)grid.GetValue(ConfiguredProperty))
            {
                grid.SetValue(ConfiguredProperty, true);
                grid.Loaded += delegate { EnsureColumnReadability(grid); };
                grid.AutoGeneratedColumns += delegate { EnsureColumnReadability(grid); };
            }
        }

        internal static void EnsureColumnReadability(DataGrid grid)
        {
            if (grid == null) return;
            foreach (DataGridColumn column in grid.Columns)
            {
                DataGridTextColumn text = column as DataGridTextColumn;
                if (text != null) UiHelpers.EnsureTextColumnReadability(text);
            }
        }

        public static void Validate(DataGrid grid, string surface)
        {
            if (grid == null) throw new InvalidOperationException(surface + ": grid is missing.");
            EnsureColumnReadability(grid);
            if (!grid.CanUserReorderColumns || !grid.CanUserResizeColumns || !grid.CanUserSortColumns)
                throw new InvalidOperationException(surface + ": column sort/reorder/resize governance is missing.");
            if (grid.EnableColumnVirtualization || !grid.EnableRowVirtualization)
                throw new InvalidOperationException(surface + ": virtualization governance is invalid.");
            if (!GridRuntimeSupport.HasClipboardMenu(grid))
                throw new InvalidOperationException(surface + ": clipboard governance is missing.");
            if (!HorizontalScrollSupport.IsEnabled(grid))
                throw new InvalidOperationException(surface + ": grid-level horizontal wheel/touchpad support is missing.");
            if (ScrollViewer.GetHorizontalScrollBarVisibility(grid) != ScrollBarVisibility.Auto)
                throw new InvalidOperationException(surface + ": horizontal scrollbar must use Auto semantics.");
            foreach (DataGridTextColumn text in grid.Columns.OfType<DataGridTextColumn>())
            {
                if (text.MinWidth < 40) throw new InvalidOperationException(surface + ": text column has no readability floor.");
                if (!UiHelpers.HasCellToolTip(text)) throw new InvalidOperationException(surface + ": text column has no full-value/detail tooltip.");
            }
        }

        private static ScrollViewer FindScrollViewer(DependencyObject root)
        {
            if (root == null) return null;
            int count = VisualTreeHelper.GetChildrenCount(root);
            for (int i=0;i<count;i++)
            {
                DependencyObject child=VisualTreeHelper.GetChild(root,i);
                ScrollViewer viewer=child as ScrollViewer;
                if(viewer!=null) return viewer;
                viewer=FindScrollViewer(child);
                if(viewer!=null) return viewer;
            }
            return null;
        }

        private static DataGrid CreateScrollProbeGrid()
        {
            DataGrid grid = UiHelpers.CreateReadOnlyGrid();
            grid.Width = 360;
            grid.Height = 150;
            grid.Columns.Add(new DataGridTextColumn { Header="Artist", Binding=new Binding("Artist"), SortMemberPath="Artist", Width=new DataGridLength(220,DataGridLengthUnitType.Pixel), MinWidth=160 });
            // This Star column reproduces the real Metadata Review/Read Audio CD failure class:
            // it may flex, but its readability floor must create real horizontal overflow
            // instead of collapsing until WPF decides that no scrollbar is needed.
            grid.Columns.Add(new DataGridTextColumn { Header="Title", Binding=new Binding("Title"), SortMemberPath="Title", Width=new DataGridLength(1,DataGridLengthUnitType.Star), MinWidth=180 });
            grid.Columns.Add(new DataGridTextColumn { Header="Review", Binding=new Binding("Review"), SortMemberPath="Review", Width=new DataGridLength(180,DataGridLengthUnitType.Pixel), MinWidth=120 });
            EnsureColumnReadability(grid);
            grid.ItemsSource = new [] { new ScrollProbe { Artist="A very long artist name", Title="A long title used to force horizontal overflow", Review="2 alternatives" } };
            return grid;
        }

        private static void AssertRenderedHorizontalOverflow(DataGrid grid, string phase)
        {
            HwndSourceParameters parameters=new HwndSourceParameters("DJLibrary-HorizontalScrollSelfTest-"+phase.Replace(' ','-'));
            parameters.Width=380;
            parameters.Height=180;
            parameters.WindowStyle=unchecked((int)0x80000000); // WS_POPUP: real presentation source without a visible application window.
            HwndSource host=new HwndSource(parameters);
            try
            {
                host.RootVisual=grid;
                grid.ApplyTemplate();
                grid.Measure(new Size(360,150));
                grid.Arrange(new Rect(0,0,360,150));
                grid.UpdateLayout();
                ScrollViewer viewer=FindScrollViewer(grid);
                if(viewer==null) throw new InvalidOperationException(phase + ": rendered grid has no ScrollViewer.");
                if(viewer.ScrollableWidth<=0.5) throw new InvalidOperationException(phase + ": constrained Star-column grid does not expose horizontal overflow.");
                if(viewer.ComputedHorizontalScrollBarVisibility!=Visibility.Visible) throw new InvalidOperationException(phase + ": constrained grid does not show its automatic horizontal scrollbar.");
                double target=Math.Min(viewer.ScrollableWidth,40);
                viewer.ScrollToHorizontalOffset(target);
                grid.UpdateLayout();
                if(target>0.5 && viewer.HorizontalOffset<=0.1) throw new InvalidOperationException(phase + ": horizontal offset cannot change.");
            }
            finally
            {
                host.RootVisual=null;
                host.Dispose();
            }
        }

        internal static string ValidateRenderedScrollContract()
        {
            DataGrid fresh=CreateScrollProbeGrid();
            AssertRenderedHorizontalOverflow(fresh,"Fresh layout");

            AppSettings settings=new AppSettings();
            GridLayoutSettings.Capture(settings,"scroll-governance",fresh);
            NamedGridLayout captured=GridLayoutSettings.Find(settings,"scroll-governance");
            ColumnSetting titleSetting=captured==null?null:captured.Columns.FirstOrDefault(x=>String.Equals(x.Key,"Title",StringComparison.OrdinalIgnoreCase));
            if(titleSetting==null || !String.Equals(titleSetting.WidthUnit,"Star",StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("Persistent scroll contract lost the Title Star sizing unit.");

            DataGrid restored=CreateScrollProbeGrid();
            restored.Columns[1].Width=new DataGridLength(300,DataGridLengthUnitType.Pixel);
            GridLayoutSettings.Apply(settings,"scroll-governance",restored);
            if(restored.Columns[1].Width.UnitType!=DataGridLengthUnitType.Star)
                throw new InvalidOperationException("Restored scroll contract did not restore the Title Star sizing unit.");
            AssertRenderedHorizontalOverflow(restored,"Restored layout");
            return "rendered Star-column horizontal overflow + automatic scrollbar + offset + persisted layout round-trip";
        }

        internal static string ValidateContract()
        {
            DataGrid grid = UiHelpers.CreateReadOnlyGrid();
            grid.Columns.Add(new DataGridTextColumn { Header="Title", Binding=new Binding("Title"), SortMemberPath="Title", Width=new DataGridLength(1,DataGridLengthUnitType.Star) });
            Validate(grid, "Standard grid");
            string rendered=ValidateRenderedScrollContract();
            return "grid governance: sortable + reorderable + resizable + clipboard + row virtualization + lossless/readable horizontal scrolling + " + rendered;
        }

        private sealed class ScrollProbe
        {
            public string Artist { get; set; }
            public string Title { get; set; }
            public string Review { get; set; }
        }
    }
}
